import { ISO2_TO_NUM } from './iso.mjs';
import { writeFileSync } from 'node:fs';
const entries = Object.entries(ISO2_TO_NUM);
const rows = [];
for (let i = 0; i < entries.length; i += 8) {
  rows.push('  ' + entries.slice(i, i + 8).map(([k, v]) => `${k}: '${v}'`).join(', ') + ',');
}
writeFileSync(new URL('../src/data/iso2.js', import.meta.url),
`// ISO 3166-1 alpha-2 -> numeric-3: the join between the ONS trade API (which keys countries
// by alpha-2) and the world-atlas TopoJSON (which keys features by numeric-3).
// Generated by scripts/gen-iso.mjs from scripts/iso.mjs — edit the source, not this file.
export const ISO2_TO_NUM = {
${rows.join('\n')}
};
`);
console.log('wrote src/data/iso2.js —', entries.length, 'codes');
